apiVersion: autoscaling.tsm.tanzu.vmware.com/v1alpha1
kind: Definition
metadata:
  name: order
  namespace: fitness
  labels:
    app: order
spec:
  scaleTargetRef:
    kubernetes:
      kind: Deployment
      name: order
  scaleRule:
    mode: EFFICIENCY
    enabled: true
    instances:
      min: 1
      max: 5
    trigger:
      gracePeriodSeconds: 30
      metric:
        name: CPUUsagePercent
        scaleUp: 20
        scaleDown: 10
