---
apiVersion: autoscaling.tsm.tanzu.vmware.com/v1alpha1
kind: Definition
metadata:
  name: shopping
  namespace: fitness
  labels:
    app: shopping
spec:
  scaleTargetRef:
    kubernetes:
      kind: Deployment
      name: shopping
  scaleRule:
    mode: EFFICIENCY
    enabled: true
    instances:
      min: 1
      max: 5
    trigger:
      gracePeriodSeconds: 30
      metric:
        name: CPUUsagePercent
        scaleUp: 10
        scaleDown: 5
