apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth.catalog.acme.local6
spec:
  selector:
    matchLabels:
      app: catalog.acme.local
  action: ALLOW 
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/*"]
