apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth.payment4
spec:
  selector:
    matchLabels:
      app: payment
  action: ALLOW 
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/*"]
