apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth.shopping13
spec:
  selector:
    matchLabels:
      app: shopping
  action: ALLOW 
  rules:
  - to:
    - operation:
        methods: ["POST"]
        paths: ["/cart/item/add/*"]
